"""Frozen edition integrity, migration and single-attempt failure boundaries."""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
from types import SimpleNamespace
from typing import Any
from unittest.mock import Mock

import httpx
import pytest
import respx

from digest.adapters.storage import edition as edition_storage
from digest.application import prepared_delivery
from digest.delivery import edition
from digest.radar.summarizer import ArticleSummary

NOW = datetime(2026, 10, 4, 12, tzinfo=timezone.utc)
API = "https://api.telegram.org/bottoken/sendMessage"


@pytest.fixture(autouse=True)
def credentials(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("TELEGRAM_CHAT_ID", "123")
    monkeypatch.setenv("TELEGRAM_BOT_TOKEN", "token")
    for name in ("ALL_PROXY", "all_proxy", "HTTP_PROXY", "http_proxy", "HTTPS_PROXY", "https_proxy"):
        monkeypatch.delenv(name, raising=False)


def prepare(tmp_path: Path, *, long: bool = False) -> tuple[dict[str, Any], str, str]:
    config = SimpleNamespace(telegram=SimpleNamespace(bot_username="mybot"), radar=SimpleNamespace(language="en"))
    articles = [ArticleSummary("Frozen title", "https://example.com/1", "Source", "AI", "Frozen summary")]
    if long:
        articles.append(ArticleSummary("Second", "https://example.com/2", "Other", "AI", "word " * 1600))
    path, ready_sha = edition.prepare_edition(
        articles,
        config,
        cache_dir=tmp_path,
        now=NOW,
        canonical_metadata={"cards": [{"title": "Canonical title"}], "config_sha256": "old config"},
        presentation_metadata={"language": "ru"},
        checkpoint_refs={},
        producing_engine={"commit": "old engine", "prompt": "old prompt"},
    )
    _, claim_sha = edition.claim_edition(ready_sha, cache_dir=tmp_path, now=NOW)
    return json.loads(path.read_text()), ready_sha, claim_sha


def success(message_id: int = 1, owner: int = 123) -> httpx.Response:
    return httpx.Response(200, json={"ok": True, "result": {"message_id": message_id, "chat": {"id": owner}}})


@respx.mock
async def test_sender_uses_frozen_payload_without_rendering_or_config(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    manifest, ready, claim = prepare(tmp_path)
    renderer = Mock(side_effect=AssertionError("sender rendered"))
    monkeypatch.setattr(prepared_delivery, "render_compact_publication", renderer)
    route = respx.post(API).mock(return_value=success())
    result = await edition.send_prepared_edition(
        ready, claim, cache_dir=tmp_path, enabled=True, bot_username="mybot", now=NOW
    )
    assert result.complete and result.sent == 1
    assert manifest["schema"] == 2
    assert set(result.article_source_map) == result.delivered_hashes
    assert json.loads(route.calls[0].request.content) == manifest["payloads"][0]
    renderer.assert_not_called()
    assert manifest["canonical_metadata"]["cards"][0]["title"] == "Canonical title"
    assert manifest["producing_engine"]["commit"] == "old engine"
    receipts = json.loads((tmp_path / edition.RECEIPTS_FILE).read_text())
    assert receipts["schema"] == 1
    assert json.loads((tmp_path / edition.CLAIM_FILE).read_text())["schema"] == 1
    assert receipts["confirmed"][0]["message_id"] == 1
    edition.mark_applied(ready, cache_dir=tmp_path)
    again = await edition.send_prepared_edition(
        ready, claim, cache_dir=tmp_path, enabled=True, bot_username="mybot", now=NOW + timedelta(days=2)
    )
    assert again.complete and route.call_count == 1


def _legacy_collision(tmp_path: Path) -> tuple[str, str]:
    """Exact synthetic v1 records generated by the pre-migration engine."""
    fixture = Path(__file__).parent / "fixtures" / "prepared_edition_v1"
    for path in fixture.iterdir():
        (tmp_path / path.name).write_bytes(path.read_bytes())
    return (
        hashlib.sha256((tmp_path / edition.READY_FILE).read_bytes()).hexdigest(),
        hashlib.sha256((tmp_path / edition.CLAIM_FILE).read_bytes()).hexdigest(),
    )


@respx.mock
async def test_confirmed_legacy_collision_remains_readable_without_resend(tmp_path: Path) -> None:
    ready, claim = _legacy_collision(tmp_path)
    original = {path.name: path.read_bytes() for path in tmp_path.iterdir()}
    assert edition.inspect_edition(cache_dir=tmp_path, now=NOW)[2] == "confirmed"
    route = respx.post(API).mock(return_value=success())
    result = await edition.send_prepared_edition(
        ready,
        claim,
        cache_dir=tmp_path,
        enabled=True,
        bot_username="mybot",
        now=NOW + timedelta(days=2),
    )
    assert result.complete and result.sent == 2
    assert result.article_source_map == {"cdb96691": "B"}
    assert route.call_count == 0
    assert {path.name: path.read_bytes() for path in tmp_path.iterdir()} == original


@respx.mock
async def test_unstarted_legacy_collision_blocks_before_claim_or_post(tmp_path: Path) -> None:
    ready, claim = _legacy_collision(tmp_path)
    claim_path = tmp_path / edition.CLAIM_FILE
    original_claim = claim_path.read_bytes()
    claim_path.unlink()
    (tmp_path / edition.RECEIPTS_FILE).unlink()
    with pytest.raises(ValueError, match="ambiguous article vote"):
        edition.claim_edition(ready, cache_dir=tmp_path, now=NOW)
    assert not claim_path.exists()
    claim_path.write_bytes(original_claim)
    route = respx.post(API).mock(return_value=success())
    with pytest.raises(ValueError, match="ambiguous article vote"):
        await edition.send_prepared_edition(
            ready,
            claim,
            cache_dir=tmp_path,
            enabled=True,
            bot_username="mybot",
            now=NOW,
        )
    assert not (tmp_path / edition.RECEIPTS_FILE).exists()
    assert route.call_count == 0


@respx.mock
async def test_full_vote_identities_survive_frozen_send_and_source_inclusion(tmp_path: Path) -> None:
    from digest.domain.catalog.source_rules import record_delivered_articles
    from digest.domain.catalog.sources import SourceStats

    config = SimpleNamespace(telegram=SimpleNamespace(bot_username="mybot"), radar=SimpleNamespace(language="en"))
    articles = [
        ArticleSummary(
            f"Synthetic collision article {number}",
            f"https://example.invalid/article/{number}",
            source,
            "Tech",
            "Synthetic supplied evidence",
        )
        for number, source in ((42028, "A"), (53130, "B"))
    ]
    path, ready = edition.prepare_edition(articles, config, cache_dir=tmp_path, now=NOW)
    data = json.loads(path.read_text())
    _, claim = edition.claim_edition(ready, cache_dir=tmp_path, now=NOW)
    route = respx.post(API).mock(return_value=success())
    result = await edition.send_prepared_edition(
        ready,
        claim,
        cache_dir=tmp_path,
        enabled=True,
        bot_username="mybot",
        now=NOW,
    )
    expected = {item["full_hash"]: item["source"] for item in data["articles"]}
    assert len(expected) == 2 and {identity[:8] for identity in expected} == {"cdb96691"}
    assert result.article_source_map == expected
    assert result.delivered_hashes == set(expected)
    assert json.loads(route.calls[0].request.content) == data["payloads"][0]
    rows = data["payloads"][0]["reply_markup"]["inline_keyboard"]
    assert [row[0]["url"] for row in rows] == [f"https://t.me/mybot?start=vote_g_{identity}" for identity in expected]
    stats = {source: SourceStats(source) for source in ("A", "B", "Wrong legacy source")}
    record_delivered_articles(
        stats,
        result.delivered_hashes,
        {"cdb96691": "Wrong legacy source", **result.article_source_map},
        NOW.date(),
    )
    assert [stats[source].articles_included_in_digest for source in stats] == [1, 1, 0]


@pytest.mark.parametrize(
    "receipt",
    [
        {"ok": True},
        {"ok": True, "result": {}},
        {"ok": True, "result": {"message_id": 0, "chat": {"id": 123}}},
        {"ok": True, "result": {"message_id": True, "chat": {"id": 123}}},
        {"ok": True, "result": {"message_id": 1, "chat": {"id": 999}}},
        {"ok": True, "result": {"message_id": 1, "chat": {"id": "123"}}},
        {"ok": False},
    ],
)
@respx.mock
async def test_ambiguous_receipt_holds_and_never_replays(tmp_path: Path, receipt: dict[str, Any]) -> None:
    _, ready, claim = prepare(tmp_path)
    route = respx.post(API).mock(return_value=httpx.Response(200, json=receipt))
    result = await edition.send_prepared_edition(
        ready, claim, cache_dir=tmp_path, enabled=True, bot_username="mybot", now=NOW
    )
    assert result.outcome == "unknown" and result.sent == 0
    assert edition.inspect_edition(cache_dir=tmp_path, now=NOW)[2] == "held"
    with pytest.raises(ValueError, match="held"):
        await edition.send_prepared_edition(
            ready, claim, cache_dir=tmp_path, enabled=True, bot_username="mybot", now=NOW
        )
    assert route.call_count == 1


@pytest.mark.parametrize("status", [400, 429, 500, 302])
@respx.mock
async def test_http_errors_never_retry_or_fallback(tmp_path: Path, status: int) -> None:
    _, ready, claim = prepare(tmp_path)
    route = respx.post(API).mock(return_value=httpx.Response(status, json={"ok": False}))
    result = await edition.send_prepared_edition(
        ready, claim, cache_dir=tmp_path, enabled=True, bot_username="mybot", now=NOW
    )
    assert result.sent == 0 and route.call_count == 1
    with pytest.raises(ValueError, match="held"):
        await edition.send_prepared_edition(
            ready, claim, cache_dir=tmp_path, enabled=True, bot_username="mybot", now=NOW
        )


@respx.mock
async def test_partial_receipts_keep_only_complete_article_coverage(tmp_path: Path) -> None:
    manifest, ready, claim = prepare(tmp_path, long=True)
    route = respx.post(API).mock(side_effect=[success(), httpx.ReadTimeout("lost receipt")])
    result = await edition.send_prepared_edition(
        ready, claim, cache_dir=tmp_path, enabled=True, bot_username="mybot", now=NOW
    )
    assert result.confirmed_chunks == 1 and result.attempted_chunks == 2 and result.outcome == "unknown"
    assert result.delivered_hashes == {manifest["articles"][0]["full_hash"]}
    assert route.call_count == 2
    with pytest.raises(ValueError, match="held"):
        await edition.send_prepared_edition(
            ready, claim, cache_dir=tmp_path, enabled=True, bot_username="mybot", now=NOW
        )


@pytest.mark.parametrize("failure", ["attempted", "confirmed", "terminal"])
@respx.mock
async def test_receipt_write_failure_retains_hold_without_replay(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    failure: str,
) -> None:
    _, ready, claim = prepare(tmp_path)
    original_write = edition_storage.write_record

    def crash(path: Path, value: dict[str, Any], *, exclusive: bool = False) -> str:
        if (
            failure == "attempted"
            and value.get("attempted") == 1
            or failure == "confirmed"
            and value.get("confirmed")
            or failure == "terminal"
            and value.get("state") == "confirmed"
        ):
            raise OSError("disk lost")
        return original_write(path, value, exclusive=exclusive)

    monkeypatch.setattr(edition_storage, "write_record", crash)
    route = respx.post(API).mock(return_value=success())
    with pytest.raises(OSError):
        await edition.send_prepared_edition(
            ready, claim, cache_dir=tmp_path, enabled=True, bot_username="mybot", now=NOW
        )
    persisted = json.loads((tmp_path / edition.RECEIPTS_FILE).read_bytes())
    assert persisted["state"] == "sending" and persisted["applied"] is False
    assert persisted["attempted"] == (0 if failure == "attempted" else 1)
    assert len(persisted["confirmed"]) == (1 if failure == "terminal" else 0)
    monkeypatch.setattr(edition_storage, "write_record", original_write)
    with pytest.raises(ValueError, match="held"):
        await edition.send_prepared_edition(
            ready, claim, cache_dir=tmp_path, enabled=True, bot_username="mybot", now=NOW
        )
    assert route.call_count == (0 if failure == "attempted" else 1)


@pytest.mark.parametrize("change", ["ready_hash", "claim_hash", "owner", "expired", "disabled", "tamper"])
@respx.mock
async def test_validation_blocks_before_http(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    change: str,
) -> None:
    manifest, ready, claim = prepare(tmp_path)
    if change == "ready_hash":
        ready = "0" * 64
    elif change == "claim_hash":
        claim = "0" * 64
    elif change == "owner":
        monkeypatch.setenv("TELEGRAM_CHAT_ID", "999")
    elif change == "tamper":
        manifest["payloads"][0]["text"] = "changed"
        (tmp_path / edition.READY_FILE).write_text(json.dumps(manifest))
        ready = hashlib.sha256((tmp_path / edition.READY_FILE).read_bytes()).hexdigest()
    with pytest.raises(ValueError):
        await edition.send_prepared_edition(
            ready,
            claim,
            cache_dir=tmp_path,
            enabled=change != "disabled",
            bot_username="mybot",
            now=NOW + timedelta(days=1) if change == "expired" else NOW,
        )
    assert not respx.calls


def test_inspect_claim_and_no_ready_overwrite(tmp_path: Path) -> None:
    _, ready, _ = prepare(tmp_path)
    assert edition.inspect_edition(cache_dir=tmp_path, now=NOW)[2] == "held"
    with pytest.raises(FileExistsError):
        edition.claim_edition(ready, cache_dir=tmp_path, now=NOW)
    with pytest.raises(ValueError, match="held"):
        prepare(tmp_path)


@pytest.mark.parametrize("state", ["reserved", "sending", "partial", "unknown"])
def test_legacy_migration_blocks_duplicate(tmp_path: Path, state: str) -> None:
    accepted = 1 if state in {"partial", "confirmed"} else 0
    marker = {
        "schema": 1,
        "generation": "a" * 32,
        "date": NOW.date().isoformat(),
        "config_sha256": "b" * 64,
        "owner_sha256": "c" * 64,
        "state": state,
        "accepted_count": accepted,
        "attempted_count": accepted,
    }
    (tmp_path / "compact_issue.json").write_text(json.dumps(marker))
    assert edition.inspect_edition(cache_dir=tmp_path, now=NOW)[2] == ("confirmed" if state == "confirmed" else "held")
    with pytest.raises(ValueError, match="Legacy"):
        prepare(tmp_path)


def test_expired_unclaimed_edition_can_be_replaced(tmp_path: Path) -> None:
    prepare(tmp_path)
    (tmp_path / edition.CLAIM_FILE).unlink()
    assert edition.inspect_edition(cache_dir=tmp_path, now=NOW)[2] == "ready"
    assert edition.inspect_edition(cache_dir=tmp_path, now=NOW + timedelta(days=1))[2] == "expired"
    config = SimpleNamespace(telegram=SimpleNamespace(bot_username=""), radar=SimpleNamespace(language="en"))
    with pytest.raises(ValueError, match="eligible"):
        edition.prepare_edition(
            [ArticleSummary("A", "https://a", "S", "C", "text")], config, cache_dir=tmp_path, now=NOW
        )
    edition.prepare_edition(
        [ArticleSummary("A", "https://a", "S", "C", "text")], config, cache_dir=tmp_path, now=NOW + timedelta(days=1)
    )


@respx.mock
async def test_unapplied_confirmation_holds_across_days_and_cannot_replay(tmp_path: Path) -> None:
    _, ready, claim = prepare(tmp_path)
    route = respx.post(API).mock(return_value=success())
    await edition.send_prepared_edition(
        ready,
        claim,
        cache_dir=tmp_path,
        enabled=True,
        bot_username="mybot",
        now=NOW,
    )
    assert edition.inspect_edition(cache_dir=tmp_path, now=NOW + timedelta(days=1))[2] == "held"
    with pytest.raises(ValueError, match="held"):
        await edition.send_prepared_edition(
            ready,
            claim,
            cache_dir=tmp_path,
            enabled=True,
            bot_username="mybot",
            now=NOW,
        )
    assert route.call_count == 1
    edition.mark_applied(ready, cache_dir=tmp_path)
    assert edition.inspect_edition(cache_dir=tmp_path, now=NOW)[2] == "confirmed"
    assert edition.inspect_edition(cache_dir=tmp_path, now=NOW + timedelta(days=1))[2] == "expired"


@respx.mock
async def test_changed_bot_identity_cannot_send(tmp_path: Path) -> None:
    _, ready, claim = prepare(tmp_path)
    with pytest.raises(ValueError, match="identity"):
        await edition.send_prepared_edition(
            ready,
            claim,
            cache_dir=tmp_path,
            enabled=True,
            bot_username="differentbot",
            now=NOW,
        )
    assert not respx.calls
    assert not (tmp_path / edition.RECEIPTS_FILE).exists()


@respx.mock
async def test_definite_partial_error_differs_from_uncertain_receipt(tmp_path: Path) -> None:
    _, ready, claim = prepare(tmp_path, long=True)
    route = respx.post(API).mock(side_effect=[success(), httpx.Response(400, text="not json")])
    result = await edition.send_prepared_edition(
        ready,
        claim,
        cache_dir=tmp_path,
        enabled=True,
        bot_username="mybot",
        now=NOW,
    )
    assert result.outcome == "failed"
    receipts = json.loads((tmp_path / edition.RECEIPTS_FILE).read_text())
    assert receipts["state"] == "partial" and route.call_count == 2
    edition.mark_applied(ready, cache_dir=tmp_path)
    assert edition.inspect_edition(cache_dir=tmp_path, now=NOW + timedelta(days=5))[2] == "held"


@respx.mock
async def test_checkpoint_bytes_bound_at_claim_and_send(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.chdir(tmp_path)
    checkpoint = tmp_path / "archive.md"
    checkpoint.write_text("canonical approved archive")
    digest = hashlib.sha256(checkpoint.read_bytes()).hexdigest()
    config = SimpleNamespace(telegram=SimpleNamespace(bot_username="mybot"), radar=SimpleNamespace(language="en"))
    path, ready = edition.prepare_edition(
        [ArticleSummary("Title", "https://example.com", "Source", "AI", "Summary")],
        config,
        cache_dir=tmp_path / "cache",
        now=NOW,
        checkpoint_refs={"archive.md": digest},
    )
    checkpoint.write_text("modified")
    with pytest.raises(ValueError, match="checkpoint hash"):
        edition.claim_edition(ready, cache_dir=path.parent, now=NOW)
    checkpoint.write_text("canonical approved archive")
    _, claim = edition.claim_edition(ready, cache_dir=path.parent, now=NOW)
    checkpoint.write_text("modified again")
    with pytest.raises(ValueError, match="checkpoint hash"):
        await edition.send_prepared_edition(
            ready,
            claim,
            cache_dir=path.parent,
            enabled=True,
            bot_username="mybot",
            now=NOW,
        )
    assert not respx.calls


@pytest.mark.parametrize("reference", ["/tmp/foreign", "../outside", "archive/../bad", "./archive", "a//b"])
def test_checkpoint_paths_cannot_escape_runtime(tmp_path: Path, reference: str) -> None:
    config = SimpleNamespace(telegram=SimpleNamespace(bot_username="mybot"), radar=SimpleNamespace(language="en"))
    with pytest.raises(ValueError, match="Invalid"):
        edition.prepare_edition(
            [ArticleSummary("Title", "https://example.com", "Source", "AI", "Summary")],
            config,
            cache_dir=tmp_path,
            now=NOW,
            checkpoint_refs={reference: "a" * 64},
        )


def test_receipt_binding_tampering_blocks_inspection(tmp_path: Path) -> None:
    _, ready, claim = prepare(tmp_path)
    (tmp_path / edition.RECEIPTS_FILE).write_text(
        json.dumps(
            {
                "schema": 1,
                "ready_sha256": ready,
                "claim_sha256": "0" * 64,
                "state": "confirmed",
                "attempted": 1,
                "applied": True,
                "confirmed": [{"chunk": 0, "message_id": 1, "owner_sha256": hashlib.sha256(b"123").hexdigest()}],
            }
        )
    )
    assert claim != "0" * 64
    with pytest.raises(ValueError, match="receipts"):
        edition.inspect_edition(cache_dir=tmp_path, now=NOW)


def test_ready_window_ends_at_utc_midnight_not_twenty_four_hours_after_preparation(tmp_path: Path) -> None:
    config = SimpleNamespace(telegram=SimpleNamespace(bot_username="mybot"), radar=SimpleNamespace(language="en"))
    cards = [ArticleSummary("A", "https://example.com/a", "S", "C", "Claim")]
    before = NOW.replace(hour=23, minute=59)
    midnight = (NOW + timedelta(days=1)).replace(hour=0)
    _, ready = edition.prepare_edition(cards, config, cache_dir=tmp_path, now=before)
    assert edition.inspect_edition(cache_dir=tmp_path, now=before)[2] == "ready"
    assert edition.inspect_edition(cache_dir=tmp_path, now=midnight)[2] == "expired"
    with pytest.raises(ValueError):
        edition.claim_edition(ready, cache_dir=tmp_path, now=midnight)
    with pytest.raises(ValueError):
        edition.prepare_edition(
            cards, config, cache_dir=tmp_path / "other", now=before, expires_at=midnight + timedelta(minutes=1)
        )


def prepare_tomorrow(tmp_path: Path) -> tuple[Path, str]:
    config = SimpleNamespace(telegram=SimpleNamespace(bot_username="mybot"), radar=SimpleNamespace(language="en"))
    return edition.prepare_edition(
        [ArticleSummary("Tomorrow", "https://example.com/tomorrow", "Source", "AI", "Prepared summary")],
        config,
        cache_dir=tmp_path,
        now=NOW,
        publication_date=(NOW + timedelta(days=1)).date(),
    )


@respx.mock
async def test_prepare_tomorrow_after_confirmed_today_and_send_only_in_window(tmp_path: Path) -> None:
    _, ready, claim = prepare(tmp_path)
    route = respx.post(API).mock(return_value=success())
    await edition.send_prepared_edition(
        ready,
        claim,
        cache_dir=tmp_path,
        enabled=True,
        bot_username="mybot",
        now=NOW,
    )
    edition.mark_applied(ready, cache_dir=tmp_path)
    assert edition.inspect_edition(cache_dir=tmp_path, now=NOW)[2] == "confirmed"
    path, tomorrow_ready = prepare_tomorrow(tmp_path)
    manifest = json.loads(path.read_text())
    start = NOW.replace(hour=0) + timedelta(days=1)
    assert manifest["created_at"] == NOW.isoformat()
    assert manifest["window_start"] == start.isoformat()
    assert manifest["window_end"] == (start + timedelta(days=1)).isoformat()
    assert manifest["expires_at"] == manifest["window_end"]
    assert edition.inspect_edition(cache_dir=tmp_path, now=NOW)[2] == "pending_window"
    with pytest.raises(ValueError):
        edition.claim_edition(tomorrow_ready, cache_dir=tmp_path, now=NOW)
    assert not (tmp_path / edition.CLAIM_FILE).exists()
    with pytest.raises(ValueError, match="eligible"):
        prepare_tomorrow(tmp_path)
    frozen_future = path.read_bytes()
    with pytest.raises(ValueError, match="eligible"):
        prepare(tmp_path)  # Default today must not displace the prepared future edition.
    assert path.read_bytes() == frozen_future
    assert edition.inspect_edition(cache_dir=tmp_path, now=start)[2] == "ready"
    _, tomorrow_claim = edition.claim_edition(tomorrow_ready, cache_dir=tmp_path, now=start)
    with pytest.raises(ValueError):
        await edition.send_prepared_edition(
            tomorrow_ready,
            tomorrow_claim,
            cache_dir=tmp_path,
            enabled=True,
            bot_username="mybot",
            now=NOW,
        )
    assert route.call_count == 1
    result = await edition.send_prepared_edition(
        tomorrow_ready,
        tomorrow_claim,
        cache_dir=tmp_path,
        enabled=True,
        bot_username="mybot",
        now=start,
    )
    assert result.complete and route.call_count == 2


def test_future_prepare_preserves_unresolved_claim_hold(tmp_path: Path) -> None:
    prepare(tmp_path)
    ready_bytes = (tmp_path / edition.READY_FILE).read_bytes()
    with pytest.raises(ValueError, match="held"):
        prepare_tomorrow(tmp_path)
    assert (tmp_path / edition.READY_FILE).read_bytes() == ready_bytes


def test_legacy_confirmed_today_allows_tomorrow_but_cannot_hide_future_ready(tmp_path: Path) -> None:
    marker = {
        "schema": 1,
        "generation": "a" * 32,
        "date": NOW.date().isoformat(),
        "config_sha256": "b" * 64,
        "owner_sha256": "c" * 64,
        "state": "confirmed",
        "accepted_count": 1,
        "attempted_count": 1,
    }
    path = tmp_path / "compact_issue.json"
    path.write_text(json.dumps(marker))
    original = path.read_bytes()
    assert edition.inspect_edition(cache_dir=tmp_path, now=NOW)[2] == "confirmed"
    with pytest.raises(ValueError, match="Legacy"):
        prepare(tmp_path)
    _, ready = prepare_tomorrow(tmp_path)
    assert edition.inspect_edition(cache_dir=tmp_path, now=NOW)[2] == "pending_window"
    assert path.read_bytes() == original
    edition.claim_edition(ready, cache_dir=tmp_path, now=NOW.replace(hour=0) + timedelta(days=1))


def test_past_publication_day_rejected(tmp_path: Path) -> None:
    config = SimpleNamespace(telegram=SimpleNamespace(bot_username="mybot"), radar=SimpleNamespace(language="en"))
    with pytest.raises(ValueError, match="Publication date"):
        edition.prepare_edition(
            [ArticleSummary("Title", "https://example.com", "Source", "AI", "Summary")],
            config,
            cache_dir=tmp_path,
            now=NOW,
            publication_date=(NOW - timedelta(days=1)).date(),
        )
    assert not (tmp_path / edition.READY_FILE).exists()


def test_prepared_domain_checks_do_not_read_environment_or_checkpoint_bytes() -> None:
    import subprocess
    import sys

    code = r"""
import os
import sys
from pathlib import Path

def unexpected(*args, **kwargs):
    raise AssertionError('Domain read external state')

os.environ.get = unexpected
Path.read_bytes = unexpected
from digest.domain.delivery.edition import validate_checkpoint_reference, validate_receipts
validate_checkpoint_reference('missing/checkpoint.json', 'a' * 64)
validate_receipts({
    'ready_sha256': 'ready', 'claim_sha256': 'claim', 'state': 'confirmed',
    'attempted': 1, 'applied': False,
    'confirmed': [{'chunk': 0, 'message_id': 1, 'owner_sha256': 'explicit-owner'}],
}, 'ready', 'claim', 1, 'explicit-owner')
for name in sys.modules:
    assert not name.startswith(('httpx', 'digest.adapters', 'digest.application',
                                'digest.radar', 'digest.llm', 'digest.config'))
"""
    subprocess.run([sys.executable, "-c", code], check=True, capture_output=True, text=True)


def test_prepared_compatibility_exports_keep_value_and_entrypoint_identity() -> None:
    from digest.domain.delivery import edition as domain
    from digest.domain.editorial.summaries import ArticleSummary as Summary

    assert ArticleSummary is Summary
    for name in ("_Edition", "_PreparedArticle", "_Claim", "_ChunkReceipt", "_Receipts"):
        assert getattr(edition, name) is getattr(domain, name)
    for name in ("prepare_edition", "claim_edition", "send_prepared_edition", "inspect_edition", "mark_applied"):
        assert getattr(edition, name) is getattr(prepared_delivery, name)


async def supplement_edition(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> tuple[Any, dict[str, Any], str, datetime]:
    from dataclasses import asdict

    from tests.test_post_delivery import pending_supplement

    monkeypatch.chdir(tmp_path)
    pending = await pending_supplement(monkeypatch, long=True)
    day = datetime.fromisoformat(pending.fragment.origin.publication_day).replace(tzinfo=timezone.utc) + timedelta(
        days=1
    )
    cards = [
        ArticleSummary("Tomorrow main", "https://example.com/tomorrow", "Source", "Tech", "Main survives."),
        ArticleSummary("Final kindness", "https://example.com/kindness", "Community", "Life", "Closer survives."),
    ]
    config = SimpleNamespace(telegram=SimpleNamespace(bot_username="mybot"), radar=SimpleNamespace(language="en"))
    path, ready = edition.prepare_edition(
        cards,
        config,
        publication_date=day.date(),
        supplement=pending,
        canonical_metadata={"cards": [asdict(cards[0])], "closing": {"card": asdict(cards[1])}},
        presentation_metadata={"cards": [asdict(card) for card in cards], "closing": {"card": asdict(cards[1])}},
        notice="Unrelated footer " * 500,
    )
    return pending, json.loads(path.read_text()), ready, day + timedelta(hours=12)


@pytest.mark.asyncio
async def test_ready3_sends_frozen_multichunk_fragment_without_article_votes_or_rerender(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from digest.presentation.telegram import escape_markdownv2

    pending, manifest, ready, now = await supplement_edition(tmp_path, monkeypatch)
    assert manifest["schema"] == 3 and len(manifest["supplement"]["coverage"]["covering_chunks"]) > 1
    text = "".join(item["text"] for item in manifest["payloads"])
    escaped_fragment = escape_markdownv2(pending.fragment.text)
    assert text.count(escaped_fragment) == 1
    fragment_start = text.index(escaped_fragment)
    fragment_end = fragment_start + len(escaped_fragment)
    offset = 0
    expected_coverage = []
    for index, payload in enumerate(manifest["payloads"]):
        end = offset + len(payload["text"])
        if offset < fragment_end and fragment_start < end:
            expected_coverage.append(index)
        offset = end
    assert manifest["supplement"]["coverage"]["covering_chunks"] == expected_coverage
    assert text.index("Tomorrow main") < text.index("Irritator:") < text.index("Final kindness")
    assert "LATE QUALIFIER" in text and "One external source was unavailable" in text
    assert pending.attempt not in manifest["checkpoint_refs"]
    assert len(manifest["articles"]) == 2
    with pytest.raises(ValueError, match="schema"):
        edition_storage.read_record(Path(".cache", edition.READY_FILE), allowed_schemas=(1, 2))
    _, claim = edition.claim_edition(ready, now=now)
    monkeypatch.setattr(
        prepared_delivery, "render_compact_publication", Mock(side_effect=AssertionError("No rerender"))
    )
    with respx.mock(assert_all_called=True) as router:
        route = router.post(API).mock(
            return_value=httpx.Response(
                200,
                json={"ok": True, "result": {"message_id": 5, "chat": {"id": 12345}}},
            )
        )
        result = await edition.send_prepared_edition(ready, claim, enabled=True, bot_username="mybot", now=now)
    assert result.complete and result.sent == 2 and len(result.article_source_map) == 2
    assert all(len(identity) == 32 for identity in result.article_source_map)
    assert [json.loads(call.request.content) for call in route.calls] == manifest["payloads"]
    edition.mark_applied(ready)
    saved = json.loads(Path(pending.attempt).read_text())
    assert saved["supplement_status"] == "consumed"
    assert json.loads(Path(".cache", edition.RECEIPTS_FILE).read_text())["applied"] is True
    consumption = Path(pending.attempt).read_bytes()
    edition.mark_applied(ready)
    assert Path(pending.attempt).read_bytes() == consumption


@pytest.mark.asyncio
@pytest.mark.parametrize("outcome", ["fragment_incomplete", "later_unknown", "consume_write_failure"])
async def test_fragment_consumption_is_required_before_applied_and_independent_of_later_uncertainty(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    outcome: str,
) -> None:
    from unittest.mock import patch

    pending, manifest, ready, now = await supplement_edition(tmp_path, monkeypatch)
    _, claim = edition.claim_edition(ready, now=now)
    last_fragment_chunk = manifest["supplement"]["coverage"]["covering_chunks"][-1]
    prefix = last_fragment_chunk if outcome == "fragment_incomplete" else last_fragment_chunk + 1
    assert prefix < len(manifest["payloads"])
    receipts = {
        "schema": 1,
        "ready_sha256": ready,
        "claim_sha256": claim,
        "state": "unknown",
        "attempted": prefix + 1,
        "applied": False,
        "confirmed": [
            {"chunk": index, "message_id": index + 1, "owner_sha256": manifest["owner_sha256"]}
            for index in range(prefix)
        ],
    }
    path = Path(".cache", edition.RECEIPTS_FILE)
    edition_storage.write_record(path, receipts)
    if outcome == "consume_write_failure":
        with patch("digest.application.supplement.storage.save_attempt", side_effect=OSError("disk full")):
            with pytest.raises(OSError, match="disk full"):
                edition.mark_applied(ready)
    elif outcome == "fragment_incomplete":
        with pytest.raises(ValueError, match="not completely confirmed"):
            edition.mark_applied(ready)
    else:
        edition.mark_applied(ready)
    assert json.loads(path.read_text())["applied"] is (outcome == "later_unknown")
    saved = json.loads(Path(pending.attempt).read_text())
    assert saved["supplement_status"] == ("consumed" if outcome == "later_unknown" else "included_ready")
    assert edition.inspect_edition(now=now)[2] == "held"


@pytest.mark.asyncio
async def test_expired_unclaimed_fragment_releases_before_replacement_then_expires_day_four(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from dataclasses import asdict
    from unittest.mock import patch

    from digest.application.supplement import pending_fragment

    pending, _, old_ready, now = await supplement_edition(tmp_path, monkeypatch)
    next_day = now + timedelta(days=1)
    reused, status = pending_fragment("digests", next_day.date(), now=next_day)
    assert reused == pending and status == "eligible"
    saved = json.loads(Path(pending.attempt).read_text())
    assert saved["supplement_status"] == "pending" and saved["fragment"]["released_binding"] == {
        "ready_sha256": old_ready,
        "reason": "expired_unclaimed_ready",
    }
    original_write = edition_storage.write_record

    def write(path: Path, value: dict[str, Any], **kwargs: Any) -> str:
        if path.name == edition.READY_FILE:
            released = json.loads(Path(pending.attempt).read_text())["fragment"]["released_binding"]
            assert released["ready_sha256"] == old_ready
        return original_write(path, value, **kwargs)

    card = ArticleSummary("Later main", "https://example.com/later", "Source", "Tech", "Still whole.")
    config = SimpleNamespace(telegram=SimpleNamespace(bot_username="mybot"), radar=SimpleNamespace(language="en"))
    with patch("digest.application.prepared_delivery.storage.write_record", side_effect=write):
        _, ready = edition.prepare_edition(
            [card],
            config,
            now=next_day,
            supplement=reused,
            canonical_metadata={"cards": [asdict(card)]},
            presentation_metadata={"cards": [asdict(card)]},
        )
    rebound = json.loads(Path(pending.attempt).read_text())["fragment"]
    assert rebound["included_ready"] == ready and ready != old_ready
    expiry = next_day + timedelta(days=2)
    assert pending_fragment("digests", expiry.date(), now=expiry) == (None, "no_pending_fragment")
    terminal = json.loads(Path(pending.attempt).read_text())
    assert terminal["supplement_status"] == "expired" and terminal["supplement_reason"] == "origin_day_plus_four_utc"
    assert terminal["fragment"]["released_binding"]["ready_sha256"] == ready


@pytest.mark.asyncio
async def test_claimed_fragment_expiry_never_releases_an_uncertain_reservation(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from digest.application.supplement import pending_fragment

    pending, _, ready, now = await supplement_edition(tmp_path, monkeypatch)
    edition.claim_edition(ready, now=now)
    before = Path(pending.attempt).read_bytes()
    later = now + timedelta(days=5)
    assert pending_fragment("digests", later.date(), now=later) == (None, "unverified_pending_fragment")
    assert Path(pending.attempt).read_bytes() == before
    assert edition.inspect_edition(now=later)[2] == "held"


@pytest.mark.asyncio
async def test_frozen_fragment_corruption_blocks_claim_without_reinterpreting_it(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    pending, _, ready, now = await supplement_edition(tmp_path, monkeypatch)
    Path(pending.projection).write_text("corrupt")
    with pytest.raises(ValueError, match="checkpoint hash mismatch"):
        edition.claim_edition(ready, now=now)
    assert not Path(".cache", edition.CLAIM_FILE).exists()


@pytest.mark.asyncio
@pytest.mark.parametrize("fault", ["canonical_identity", "presented_order", "closer", "current_review", "coverage"])
async def test_ready3_structural_association_rejects_rehashed_mismatches(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    fault: str,
) -> None:
    _, manifest, _, now = await supplement_edition(tmp_path, monkeypatch)
    if fault == "canonical_identity":
        manifest["canonical_metadata"]["cards"][0]["source"] = "Other occurrence"
    elif fault == "presented_order":
        manifest["presentation_metadata"]["cards"].reverse()
    elif fault == "closer":
        manifest["presentation_metadata"]["closing"]["card"] = manifest["articles"][0]["card"]
    elif fault == "current_review":
        manifest["current_review_checkpoint"] = manifest["supplement"]["fragment"]["checkpoint"]
    else:
        manifest["supplement"]["coverage"]["covering_chunks"] = []
    for name in ("canonical", "presentation"):
        manifest[f"{name}_sha256"] = edition_storage.content_sha256(
            edition_storage.canonical_bytes(manifest[f"{name}_metadata"]),
        )
    manifest["content_sha256"] = edition_storage.content_sha256(
        edition_storage.canonical_bytes(
            {key: value for key, value in manifest.items() if key != "content_sha256"},
        )
    )
    with pytest.raises(ValueError, match="prepared edition"):
        edition_storage.validate_manifest_record(manifest, "12345", now)


@pytest.mark.asyncio
@pytest.mark.parametrize("boundary", ["ready_to_reservation", "reservation_to_claim"])
async def test_fragment_reservation_crashes_hold_frozen_work_without_consuming_or_replaying(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    boundary: str,
) -> None:
    from dataclasses import asdict
    from unittest.mock import patch

    from digest.application.supplement import pending_fragment
    from tests.test_post_delivery import pending_supplement

    monkeypatch.chdir(tmp_path)
    pending = await pending_supplement(monkeypatch)
    now = datetime.fromisoformat(pending.fragment.origin.publication_day).replace(tzinfo=timezone.utc) + timedelta(
        days=1
    )
    config = SimpleNamespace(telegram=SimpleNamespace(bot_username="mybot"), radar=SimpleNamespace(language="en"))
    card = ArticleSummary("Next", "https://example.com/next", "Source", "Tech", "Main copy.")
    arguments = {
        "canonical_metadata": {"cards": [asdict(card)]},
        "presentation_metadata": {"cards": [asdict(card)]},
        "supplement": pending,
        "now": now,
    }
    if boundary == "ready_to_reservation":
        with patch("digest.application.supplement.storage.save_attempt", side_effect=OSError("reservation failed")):
            with pytest.raises(OSError, match="reservation failed"):
                edition.prepare_edition([card], config, **arguments)
        ready = hashlib.sha256(Path(".cache", edition.READY_FILE).read_bytes()).hexdigest()
        with pytest.raises(ValueError, match="reservation"):
            edition.claim_edition(ready, now=now)
        assert json.loads(Path(pending.attempt).read_text())["supplement_status"] == "pending"
    else:
        _, ready = edition.prepare_edition([card], config, **arguments)
        original_write = edition_storage.write_record

        def fail_after_claim(path: Path, value: dict[str, Any], **kwargs: Any) -> str:
            original_write(path, value, **kwargs)
            raise OSError("claim persistence barrier failed")

        with patch("digest.application.prepared_delivery.storage.write_record", side_effect=fail_after_claim):
            with pytest.raises(OSError, match="claim persistence"):
                edition.claim_edition(ready, now=now)
        assert pending_fragment("digests", (now + timedelta(days=1)).date(), now=now + timedelta(days=1)) == (
            None,
            "unverified_pending_fragment",
        )
        assert json.loads(Path(pending.attempt).read_text())["supplement_status"] == "included_ready"


@pytest.mark.asyncio
@pytest.mark.parametrize("missing", ["old_ready", "release_proof"])
async def test_unclaimed_fragment_reuse_requires_retained_old_ready_and_release_proof(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    missing: str,
) -> None:
    from dataclasses import asdict

    from digest.application.supplement import pending_fragment

    pending, _, _, now = await supplement_edition(tmp_path, monkeypatch)
    now += timedelta(days=1)
    path = Path(".cache", edition.READY_FILE)
    if missing == "old_ready":
        original = Path(pending.attempt).read_bytes()
        path.unlink()
        assert pending_fragment("digests", now.date(), now=now) == (None, "unverified_pending_fragment")
        assert Path(pending.attempt).read_bytes() == original
    else:
        record = json.loads(Path(pending.attempt).read_text())
        record["supplement_status"] = "pending"
        record["fragment"]["included_ready"] = None
        Path(pending.attempt).write_text(json.dumps(record))
        original_ready = path.read_bytes()
        card = ArticleSummary("Next", "https://example.com/next", "Source", "Tech", "Main copy.")
        config = SimpleNamespace(telegram=SimpleNamespace(bot_username="mybot"), radar=SimpleNamespace(language="en"))
        with pytest.raises(ValueError, match="release is not proven"):
            edition.prepare_edition(
                [card],
                config,
                now=now,
                supplement=pending,
                canonical_metadata={"cards": [asdict(card)]},
                presentation_metadata={"cards": [asdict(card)]},
            )
        assert path.read_bytes() == original_ready
